version: "3.8"
services:
    app:
        image: ghcr.io/rayhannnaaf/akuntansi-final:latest
        ports:
            - "3000:3000"
        env_file:
            - .env.production
        restart: unless-stopped
